server:
  port: 8080
  servlet:
    context-path: /back

spring:
  messages:
    encoding: utf-8
  datasource:
    url: jdbc:mysql://101.35.248.3:3306/werun?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: werundba
    password: werunpro
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
  #  redis config
  redis:
    host: 101.35.248.3
    password:
    port: 6379
    jedis:
      pool:
        #连接池最大活动连接
        max-active: 30
        #最大空闲链接
        max-idle: 10
        #超过时间
        max-wait: 10ms
        #连接池最小空闲连接
        min-idle: 3

web:
  upload:
    path: /werunImg
  resources:
    static-locations: classpath:/static/,classpath:/templates/,file:${web.upload.path}
mybatis:
  configuration:
    map-underscore-to-camel-case: true


FileOp:
  upload:
    path: /Users/gonghe/work/werunImg/
    headPath: /Users/gonghe/work/werunImg/head/
    goodPath: /Users/gonghe/work/werunImg/good/
    postPath: /Users/gonghe/work/werunImg/post/
  werunImg:
    head: http://192.168.10.107:9997/head/
    good: http://192.168.10.107:9997/good/
    post: http://192.168.10.107:9997/post/


#logging.level.com.werun.back.dao: debug